apiVersion: v1
kind: Service
metadata:
  name: dummy-service
spec:
  type: NodePort
  selector:
    app: dummy-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081

