apiVersion: v1
kind: Service
metadata:
  name: ta-service
spec:
  type: NodePort
  selector:
    app: ta-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082

